#!/bin/bash
set -euo pipefail

install_configs() {
	sudo cp -r .rootfs/* /
	cp -r .[^.]* ~
	mv ~/.git ~/.dotfiles
	echo 'Configs installed'
}

change_acpi_events() {
	sudo sed -i 's/^#\?HandlePowerKey=.*/HandlePowerKey=suspend/' /etc/systemd/logind.conf
	echo "Power key suspend configured"
}

config_pacman() {
	sudo sed -i '/^#Color/s/^#//' /etc/pacman.conf
	echo 'Pacman color enabled'

	sudo sed -i '/^#\[multilib\]/,/^#Include/s/^#//' /etc/pacman.conf
	echo 'Multilib enabled'
}

disable_debug_makepkg() {
	sudo sed -i '/^OPTIONS/s/ debug/ !debug/' /etc/makepkg.conf
	echo 'Debug makepkg disabled'
}

enable_zram() {
	sudo pacman -Sy --needed zram-generator
	sudo systemctl daemon-reload
	sudo systemctl start systemd-zram-setup@zram0.service
	echo 'Zram enabled'
}

install_configs
change_acpi_events
config_pacman
disable_debug_makepkg
enable_zram
