#!/bin/sh
set -euo pipefail

install_configs() {
	sudo cp -r ./etc/* /etc/
	cp -r .[!.]* ~
	mv ~/.git ~/.dotfiles
	echo 'Configs installed'
}

config_pacman() {
	sudo sed -i '/^#Color/s/^#//' /etc/pacman.conf
	echo 'Pacman color enabled'

	sudo sed -i '/^#\[multilib\]/,/^#Include/s/^#//' /etc/pacman.conf
	echo 'Multilib enabled'
}

config_makepkg() {
	sudo sed -i '/^OPTIONS/s/ debug/ !debug/' /etc/makepkg.conf
	echo 'Debug makepkg disabled'

	sudo sed -i '/^CFLAGS=/s/-march=x86-64 -mtune=generic/-march=native/' /etc/makepkg.conf
	echo 'CFLAGS -march=native enabled'

	sudo sed -i '/^RUSTFLAGS=/{/-C target-cpu=native/! s/"$/ -C target-cpu=native"/}' /etc/makepkg.conf.d/rust.conf
	echo "RUSTFLAGS target-cpu=native enabled"
}

enable_zram() {
	sudo pacman -Sy --needed zram-generator
	sudo systemctl daemon-reload
	sudo systemctl start systemd-zram-setup@zram0.service
	echo 'zram enabled'
}

install_configs

config_pacman
config_makepkg
enable_zram
